### ISSUE TITLE
install doc is missing, that you should use requirements.txt

### ISSUE THREAD

**Issue by StephanJanosch** [DLR-SC/GitLab-Corpus#2]
I as python newbie did not look at requirements.txt, because install doc did miss a line like this

`
pip install -r requirements.txt
`

That should be in README.md

**Comment by schlauch** [comment]
Thanks! 

I think the confusion comes from : https://github.com/DLR-SC/GitLab-Corpus#dependencies-to-develop-this-tool => `Dependencies to develop this tool` !?

Actually, this section also describes the proper way how to use that tool as no pure user package on PyPI or similar exists.

I.e., the following would do all necessary tricks:

```
git clone <url>
cd corpus
pip install --editable .
corpus ...
```

I need to think about how to better describe that.

**Comment by StephanJanosch** [comment]
I followed that. But for some reasons requirements.txt wasn't used. As i am not a "ptyhon"isto I can't tell if pip install should have picked that file up and install deps.

Thx
