### ISSUE TITLE
does not find all all projects

### ISSUE THREAD

**Issue by StephanJanosch** [DLR-SC/GitLab-Corpus#3]
When I log into Gitlab via browser, It tells me, I have 389 projects.

There are 8 in the export. Also see **0%20 projects found**

Is the enumeration broken? I used my token. Even without login I can see more that 9 projects

**output below**

Neo4j config is not valid.
Retrieving projects...
Extracting...
  [------------------------------------]    0%20 projects found.

 Project statistics for project xxxx could not be fetched. You might need write access to fix this.
  [#-----------------------------------]    5%
 Project statistics for project xxxx could not be fetched. You might need write access to fix this.
  [#######-----------------------------]   20%  00:00:09
 Project statistics for project xxxx could not be fetched. You might need write access to fix this.
  [##########--------------------------]   30%  00:00:08
 Project statistics for project xxxx could not be fetched. You might need write access to fix this.
  [#####################---------------]   60%  00:00:03
 Project statistics for project xxxx could not be fetched. You might need write access to fix this.
  [#######################-------------]   65%  00:00:03
 Project statistics for project xxxx could not be fetched. You might need write access to fix this.
  [#########################-----------]   70%  00:00:02
 Project statistics for project xxxx could not be fetched. You might need write access to fix this.
  [###########################---------]   75%  00:00:02
 Project statistics for project xxxe could not be fetched. You might need write access to fix this.
  [##################################--]   95%  00:00:00
 Project statistics for project xxx could not be fetched. You might need write access to fix this.
  [####################################]  100%          
Exporting...

**Comment by schlauch** [comment]
It would be good to see your executed command line as well.

But have you tried the `--all-elements` option? It is mentioned in https://github.com/DLR-SC/GitLab-Corpus/blob/master/docs/source/getting-started.rst#information

And let us not forget that this is a students project in version 0.1 ;)

**Comment by schlauch** [comment]
In addition, it seems that the extractor only extract project with visibility public or internal.

**Comment by StephanJanosch** [comment]
I did not saw `--all-element`. Now it seams to work!
